name: all_nlp_app
channels:
  - defaults
dependencies:
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - openssl=1.1.1s
  - pip=22.2.2
  - python=3.8.13
  - setuptools=65.5.0
  - sqlite=3.39.3
  - wheel=0.37.1
  - pip:
    - altair==4.2.0
    - astroid==2.12.12
    - asttokens==2.1.0
    - attrs==22.1.0
    - autocorrect==2.6.1
    - backcall==0.2.0
    - backports-zoneinfo==0.2.1
    - beautifulsoup4==4.11.1
    - bertopic==0.12.0
    - black==22.10.0
    - blinker==1.5
    - brotli==1.0.9
    - catalogue==2.0.8
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - colorama==0.4.6
    - commonmark==0.9.1
    - configargparse==1.5.3
    - contourpy==1.0.6
    - coreferee-model-en==1.0.0
    - coverage==6.5.0
    - cssselect==1.2.0
    - cycler==0.11.0
    - cymem==2.0.7
    - debugpy==1.6.3
    - decorator==5.1.1
    - dill==0.3.6
    - elastic-transport==8.4.0
    - elasticsearch==8.5.0
    - en-core-web-lg==3.3.0
    - en-core-web-trf==3.3.0
    - entrypoints==0.4
    - exceptiongroup==1.0.2
    - executing==1.2.0
    - feedfinder2==0.0.4
    - feedparser==6.0.10
    - filelock==3.8.0
    - flask==2.2.2
    - flask-basicauth==0.2.0
    - flask-cors==3.0.10
    - flatbuffers==22.10.26
    - fonttools==4.38.0
    - gevent==22.10.2
    - geventhttpclient==2.0.8
    - greenlet==2.0.1
    - hdbscan==0.8.29
    - idna==3.4
    - importlib-metadata==5.0.0
    - iniconfig==1.1.1
    - ipykernel==6.17.1
    - ipython==8.6.0
    - isort==5.10.1
    - itsdangerous==2.1.2
    - jedi==0.18.1
    - jieba3k==0.35.1
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonschema==4.17.0
    - jupyter-client==7.4.5
    - jupyter-core==5.0.0
    - keras==2.10.0
    - kiwisolver==1.4.4
    - langcodes==3.3.0
    - langdetect==1.0.9
    - lazy-object-proxy==1.8.0
    - locust==2.13.0
    - lxml==4.9.1
    - markupsafe==2.1.1
    - matplotlib==3.6.2
    - matplotlib-inline==0.1.6
    - mccabe==0.7.0
    - msgpack==1.0.4
    - mypy-extensions==0.4.3
    - nest-asyncio==1.5.6
    - newsapi-python==0.2.6
    - newspaper3k==0.2.8
    - nlp-text-cleaner==1.0.11
    - nltk==3.7
    - numpy==1.20.3
    - packaging==21.3
    - pandas==1.5.1
    - parso==0.8.3
    - pathspec==0.10.2
    - pathy==0.6.2
    - pickleshare==0.7.5
    - pillow==9.3.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==2.5.4
    - prompt-toolkit==3.0.32
    - protobuf==3.20.3
    - pure-eval==0.2.2
    - pycparser==2.21
    - pydantic==1.8.2
    - pydeck==0.8.0
    - pygments==2.13.0
    - pylint==2.15.5
    - pympler==1.0.1
    - pyparsing==3.0.9
    - pyrsistent==0.19.2
    - pytest==7.2.0
    - pytest-cov==4.0.0
    - python-dateutil==2.8.2
    - pytz==2022.6
    - pytz-deprecation-shim==0.1.0.post0
    - pyyaml==5.4.1
    - pyzmq==24.0.1
    - regex==2022.10.31
    - requests==2.28.1
    - requests-file==1.5.1
    - rich==12.6.0
    - roundrobin==0.0.4
    - scipy==1.9.3
    - semver==2.13.0
    - sentence-transformers==2.2.2
    - sentencepiece==0.1.97
    - sgmllib3k==1.0.0
    - six==1.16.0
    - smart-open==5.2.1
    - smmap==5.0.0
    - soupsieve==2.3.2.post1
    - spacy-alignments==0.8.6
    - spacy-legacy==3.0.10
    - spacy-loggers==1.0.3
    - spacy-transformers==1.1.7
    - srsly==2.4.5
    - stack-data==0.6.1
    - streamlit==1.14.1
    - tenacity==8.1.0
    - termcolor==2.1.0
    - threadpoolctl==3.1.0
    - tinysegmenter==0.3
    - tldextract==3.4.0
    - tokenizers==0.12.1
    - toml==0.10.2
    - tomli==2.0.1
    - tomlkit==0.11.6
    - toolz==0.12.0
    - torch==1.10.2
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.5.0
    - transformers==4.20.1
    - typer==0.4.2
    - typing-extensions==4.4.0
    - tzdata==2022.6
    - tzlocal==4.2
    - urllib3==1.26.12
    - validators==0.20.0
    - wasabi==0.10.1
    - watchdog==2.1.9
    - wcwidth==0.2.5
    - werkzeug==2.2.2
    - wrapt==1.14.1
    - zipp==3.10.0
    - zope-event==4.5.0
    - zope-interface==5.5.1
